### ISSUE TITLE
requires spate/yii-ray:1.14

### ISSUE THREAD

**Issue by jasonmccallister** [spatie/craft-ray#1]
**Describe the bug**
This might be premature, but when installing it requires a version of yii-ray that is not available.e

**Versions**
- spatie/craft-ray package version: 1.0.0

PHP version: 7.4
Craft version (if applicable): 3.5.18

**To Reproduce**
1. composer require spatie/craft-ray

**Comment by riasvdv** [comment]
Ah yes, messed up the constraints, should be fixed in 1.0.1

**Comment by leigeber** [comment]
Also running into this but with the RC4 release of Craft 3.6, looks like a different version of yiisoft/yii2 between Craft and yii-ray.

**Comment by riasvdv** [comment]
Can you post the exact composer output you’re getting?

**Comment by jasonmccallister** [comment]
@riasvdv the 3.6 change log has more details on the new version of Craft CMS (e.g. we upgraded the version of Yii to 2.0.40)

https://github.com/craftcms/cms/blob/3.6/CHANGELOG-v3.6.md

**Comment by leigeber** [comment]
Sure thing.

```Problem 1
    - craftcms/cms 3.6.0-RC4 requires yiisoft/yii2 ~2.0.40.0 -> satisfiable by yiisoft/yii2[2.0.40].
    - spatie/craft-ray 1.0.0 requires spatie/yii-ray ^1.14 -> found spatie/yii-ray[dev-master, 0.0.1, 0.0.2, 0.0.3, 0.0.4, 1.0.0, 1.1.0] but it does not match the constraint.
    - Root composer.json requires craftcms/cms 3.6.0-RC4 -> satisfiable by craftcms/cms[3.6.0-RC4].
    - spatie/yii-ray 1.1.0 requires yiisoft/yii2 ~2.0.38.0 -> satisfiable by yiisoft/yii2[2.0.38].
    - spatie/craft-ray 1.0.1 requires spatie/yii-ray ^1.1 -> satisfiable by spatie/yii-ray[1.1.0].
    - You can only install one version of a package, so only one of these can be installed: yiisoft/yii2[2.0.0, ..., 2.0.40].
    - Root composer.json requires spatie/craft-ray ^1.0 -> satisfiable by spatie/craft-ray[1.0.0, 1.0.1].```

**Comment by riasvdv** [comment]
Okay, I've updated the version constraint of spatie/yii-ray 1.1.1, give packagist a few minutes and try again, should be fixed!
