### ISSUE TITLE
Using environment variables in settings page does not work

### ISSUE THREAD

**Issue by zizther** [spatie/craft-ray#11]
Using environment variables within the settings section for the plugin within Craft do not work. I am able to enter the same values manually to make it work.

Additionally when passing in a number via a environment variable to the `Port` it creates this error `Spatie\Ray\Client::__construct(): Argument #1 ($portNumber) must be of type int, string given`.

**Example**:
`RAY_PORT=23517`

**Versions**
Ray version: 2.0
Craft version: 4.3.3
PHP version: 8.1

**Desktop**
 - OS: MacOS
 - Version: 12.5.1

**Comment by zizther** [comment]
Any updates on this issue?

**Comment by zizther** [comment]
Following up on this, as the bot seems to have completed this issue, but still remains unresolved.
@riasvdv

**Comment by zizther** [comment]
This issue still remains a problem, is there any update on this?

**Comment by riasvdv** [comment]
Should be fixed in 2.1.1!
