### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by owldesign** [spatie/craft-ray#12]
Can't get it to run on Craft 5 Beta, is there a planned compatibility update and what is the timeline?

**Comment by russback** [comment]
Any news on this? Craft 5 is due out by the end of this month.

**Comment by riasvdv** [comment]
v2.1.0 should be able to be installed with Craft 5 now!

**Comment by Antimated** [comment]
Seems like upgrading to Craft 5 gives me a "not ready" warning. Also doesn't display compatibility for Craft 5 here:
https://plugins.craftcms.com/craft-ray?cmsConstraint=^5.0. This also shows version 2.0 whilst version 2.1.1 is already available.

EDIT: This is an issue when trying to install Ray from Craft CMS' plugin store.

![Screenshot 2024-04-04 at 11 15 28](https://github.com/spatie/craft-ray/assets/2869409/d324c95f-f61c-4086-9cba-5b2a8f3ba86c)

**Comment by riasvdv** [comment]
The plugin store wasn't updating the release information of the plugin, this should now be resolved
