### ISSUE TITLE
Use of Env Vars does not work with Ray app

### ISSUE THREAD

**Issue by zizther** [spatie/craft-ray#13]
**Describe the bug**
The plugin is meant to support Env Vars within the settings, however when using them, no logs are output to the Ray app.
It must be somewhat connected, as when using the Port value in the .env file, it throws an error, related to another issue which remains unresolved for a while https://github.com/spatie/craft-ray/issues/11.

**Versions**
2.0

**Comment by riasvdv** [comment]
Should be fixed in 2.1.1!
