### ISSUE TITLE
OutOfBoundsException Package "spatie/yii-ray" is not installed

### ISSUE THREAD

**Issue by roberttolton** [spatie/craft-ray#2]
**Describe the bug**
After installing with composer, and installing in the Control Panel, trying to use any `ray()` throws an exception.

**Versions**
Ray version: `1.10.1 (1.10.1)`

You can use `composer show` to get the version numbers of:
- spatie/craft-ray package version:  `1.1.0`

PHP version: `7.4`
Laravel version (if applicable): n/a

**To Reproduce**
1. Install Craft Ray as instructed in Docs
2. Install via Control Panel
3. Try and use ray() in any PHP or Twig template

**Expected behavior**
Should output to Ray as expected.

**Screenshots**
Plugin installed in CP: https://cloud.roberttolton.com/eDu8Ydke

**Desktop (please complete the following information):**
 - OS: macOS Catalina, using Vagrant Ubuntu VM
 - Version: ubuntu/xenial64

Ray config:

```
<?php

return [
    /*
    * This settings controls whether data should be sent to Ray.
    *
    * By default, `ray()` will only transmit data in non-production environments.
    */
    'enable' => getenv('RAY_ENABLE') ?: false,

    /*
    * The host used to communicate with the Ray app.
    * For usage in Docker on Mac or Windows, you can replace host with 'host.docker.internal'
    * For usage in Homestead on Mac or Windows, you can replace host with '10.0.2.2'
    */
    'host' => getenv('RAY_HOST') ?: 'localhost',

    /*
    * The port number used to communicate with the Ray app.
    */
    'port' => getenv('RAY_PORT') ?: 23517,

    /*
     * Absolute base path for your sites or projects in Homestead,
     * Vagrant, Docker, or another remote development server.
     */
    'remote_path' => getenv('RAY_REMOTE_PATH') ?: null,

    /*
     * Absolute base path for your sites or projects on your local
     * computer where your IDE or code editor is running on.
     */
    'local_path' => getenv('RAY_LOCAL_PATH') ?: null,

    /*
     * When this setting is enabled, the package will not try to format values sent to Ray.
     */
    'always_send_raw_values' => false,
];
```

ENV:

```
RAY_ENABLE=true
RAY_HOST=10.0.2.2
RAY_REMOTE_PATH=/vagrant
RAY_LOCAL_PATH=/Users/##/Documents/web-dev/project
```

Can confirm that with the above config and a Vagrant project, but via Laravel, works fine.

**Comment by roberttolton** [comment]
Trace:

```
OutOfBoundsException: Package "spatie/yii-ray" is not installed in /vagrant/vendor/composer/composer/src/Composer/InstalledVersions.php:110
Stack trace:
#0 /vagrant/vendor/spatie/yii-ray/src/Ray.php(123): Composer\InstalledVersions::getVersion()
#1 /vagrant/vendor/spatie/ray/src/Ray.php(448): Spatie\YiiRay\Ray->sendRequest()
#2 /vagrant/vendor/spatie/ray/src/helpers.php(32): Spatie\Ray\Ray->send()
#3 /vagrant/web/index.php(90): ray()
#4 {main}
```

**Comment by riasvdv** [comment]
Did you install using `composer require --dev` or normally?

**Comment by roberttolton** [comment]
@riasvdv I installed it using `composer require` (not `dev`) on the CLI, which the docs said was possible with Craft (?). But within the last hour, I uninstalled and removed the plugin using the CP, and then used the Craft Plugin Store to find and install Ray.

It successfully installed after that, and I no longer get warnings about it not being installed, but I can't see any difference between the composer files, so I'm not sure what Craft's install process did differently..?

Although it's not actually _working_ yet, nothing ever ends up in Ray. Can I switch-on any debug mode?

**Comment by roberttolton** [comment]
@riasvdv 

So I did some digging, showing the curl errors at this stage:

`ray/src/Client.php lines 37-39`
```
if ($curlError) {
    die($curlError);
}
```

This gives me `Failed to connect to localhost port 23517: Connection refused`

So, it's not using the host I have set in my `craft-ray.php` file.

Then, within the `__construct` of `ray/src/Ray.php` I have changed line 78 from:

```
self::$client = $client ?? self::$client ?? new Client($settings->port, $settings->host);
```

to:

```
self::$client = new Client($settings->port, $settings->host);
```

And now it works..?

**Comment by riasvdv** [comment]
I'll take a look this week, if you find a solution for this then I'd gladly accept a PR

**Comment by roberttolton** [comment]
Also noticed that if I run `composer update` in my project, it breaks `craft-ray` again.

```
Exception 'OutOfBoundsException' with message 'Package "spatie/craft-ray" is not installed'
```

I had to uninstall and remove the plugin via the Control Panel, and then re-install it via the Control Panel to get it to work.
Something about it does not like the CLI..!

**Comment by riasvdv** [comment]
Which composer version are you using?

**Comment by roberttolton** [comment]
Currently v1 still

**Comment by riasvdv** [comment]
That's probably the issue, Ray uses https://getcomposer.org/doc/07-runtime.md#installed-versions which is only available in composer 2
