### ISSUE TITLE
Unable to get Craft/Twig to recognize ray calls

### ISSUE THREAD

**Issue by acres42** [spatie/craft-ray#3]
**Describe the bug**
Installation is a bear and not working correctly.
-First I keep running into a problem on installation where I had to run `composer remove symfony/console v3.3.6` to get it to install at all. 
-Secondly, I self updated to composer 1.10.20 and Composer 2.0.9. Both versions I keep getting Twig error. "Unknown "ray" function. Did you mean "raw"?"

**Versions**
Ray version (you can see this in "About Ray"):
Version 1.12.0 (1.12.0)

You can use `composer show` to get the version numbers of:
- spatie/craft-ray package version: 
spatie/craft-ray                     1.1.0    Easily debug CraftCMS projects
spatie/macroable                     1.0.1    A trait to dynamically add methods to a class
spatie/ray                           1.19.4   Debug with Ray to fix problems faster
spatie/yii-ray                       1.2.4    Easily debug Yii apps
PHP version: 7.4.15
Laravel version (if applicable): Valet 
Craft CMS "craftcms/cms": "^3.5.10.1

**To Reproduce**
1. Go to the command line
2. Type in `composer require spatie/craft-ray`
3. See error #1
See output here: 
Problem 1
    - Installation request for spatie/craft-ray ^1.1 -> satisfiable by spatie/craft-ray[1.1.0].
    - Conclusion: remove symfony/console v3.3.6
    - Conclusion: don't install symfony/console v3.3.6
    - spatie/craft-ray 1.1.0 requires spatie/ray ^1.14 -> satisfiable by spatie/ray[1.14.0, 1.14.1, 1.15.0, 1.16.0, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.18.0, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4].
    - spatie/ray 1.14.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.14.1 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.15.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.16.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.17.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.17.1 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.17.2 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.17.3 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.17.4 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.18.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.19.0 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.19.1 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.19.2 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.19.3 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - spatie/ray 1.19.4 requires symfony/var-dumper ^4.2|^5.1 -> satisfiable by symfony/var-dumper[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.10, v4.4.11, v4.4.12, v4.4.13, v4.4.14, v4.4.15, v4.4.16, v4.4.17, v4.4.18, v4.4.19, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9, v5.1.0, v5.1.1, v5.1.10, v5.1.11, v5.1.2, v5.1.3, v5.1.4, v5.1.5, v5.1.6, v5.1.7, v5.1.8, v5.1.9, v5.2.0, v5.2.1, v5.2.2, v5.2.3].
    - symfony/var-dumper v4.2.0 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.1 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.10 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.11 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.12 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.2 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.3 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.4 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.5 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.6 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.7 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.8 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.2.9 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.0 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.1 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.10 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.11 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.2 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.3 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.4 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.5 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.6 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.7 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.8 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.3.9 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.0 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.1 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.10 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.11 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.12 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.13 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.14 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.15 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.16 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.17 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.18 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.19 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.2 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.3 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.4 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.5 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.6 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.7 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.8 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v4.4.9 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.0 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.1 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.10 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.11 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.2 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.3 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.4 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.5 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.6 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.7 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.8 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.1.9 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.2.0 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.2.1 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.2.2 conflicts with symfony/console[v3.3.6].
    - symfony/var-dumper v5.2.3 conflicts with symfony/console[v3.3.6].
    - Installation request for symfony/console (locked at v3.3.6) -> satisfiable by symfony/console[v3.3.6].
4. After overcoming this, put {{ ray('my first ray call") }} into twig template, get the "
Twig Syntax Error – Twig\Error\SyntaxError
Unknown "ray" function. Did you mean "raw"?" template error.

**Expected behavior**
Ray calls to be recognized once installed

**Screenshots**
Problem #2
![Screen Shot 2021-02-11 at 6 49 48 AM](https://user-images.githubusercontent.com/3231614/107652389-5fb9a300-6c35-11eb-9216-af5ae439fba8.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS Big Sur 
 - Version [e.g. 22] 11.0.1
 
 **Additional context**
composer file after "installation"
![Screen Shot 2021-02-11 at 6 50 54 AM](https://user-images.githubusercontent.com/3231614/107652527-87107000-6c35-11eb-8daa-2e0b246c0564.png)
Using the most recent version of Laravel Valet (2.13.19)
![Screen Shot 2021-02-11 at 6 52 06 AM](https://user-images.githubusercontent.com/3231614/107652703-b626e180-6c35-11eb-8cad-d48b1222ed86.png)

**Comment by riasvdv** [comment]
1. What was the reason for there being a `symfony/console` requirement in your composer.json? The default Craft CMS project doesn't come with this

> After overcoming this, put {{ ray('my first ray call") }} into twig template, get the "
> Twig Syntax Error – Twig\Error\SyntaxError
> Unknown "ray" function. Did you mean "raw"?" template error.

Make sure the plugin is enabled in the Craft CMS control panel

**Comment by acres42** [comment]
> 1. What was the reason for there being a `symfony/console` requirement in your composer.json? The default Craft CMS project doesn't come with this

The symfony/console-- not sure where this requirement is originating from. As you can see in my screenshot above, it is not in my composer.json. 

For more context, I am trying to use Ray on an unmodified, freshly installed instance of Craft's demo repo, [Happy Lager
](https://github.com/craftcms/demo)

> Make sure the plugin is enabled in the Craft CMS control panel

*smacks forehead* Thank you. It's been a long week :)

I installed the plugin, and I am not getting any more errors or warnings. Ray just doesn't do anything with a Ray call in the template. 

This may be another dumb question, but I should just be able to refresh the page and that should kick off my Ray, correct?

Here's a video of it doing nothing/failing silently when I refresh with the Ray call in the template (just above the Ray window)
http://g.recordit.co/sFOSgQCdjt.gif

And here's an image of my plugin settings:
![Screen Shot 2021-02-12 at 4 10 46 AM](https://user-images.githubusercontent.com/3231614/107767343-b1bc0080-6ce9-11eb-8847-33da8426567d.png)

**Comment by riasvdv** [comment]
How are you hosting your local Craft install? With something like Laravel Valet or using Docker/Homestead/Nitro?

**Comment by acres42** [comment]
> How are you hosting your local Craft install? With something like Laravel Valet or using Docker/Homestead/Nitro?

I am using Laravel Valet, most recent version.

**Comment by riasvdv** [comment]
There was an issue with the enabled state of the ray instance. I've fixed this in 1.1.3, let me know if that fixes your issue

**Comment by acres42** [comment]
@riasvdv Thank you very much! Works like a charm. That fixed it!
