### ISSUE TITLE
Twig global variable only outputs first parameter

### ISSUE THREAD

**Issue by samhibberd** [spatie/craft-ray#5]
**Describe the bug**
Only the first variable is output when adding multiple variables to the twig global `{{ ray('var1', 'var2') }}`

**Versions**
Ray: 1.12.0
spatie/craft-ray package: 1.1.3
PHP: 7.4.14

**To Reproduce**
1. Add to any twig template `{{ ray('var1', 'var2') }}`
2. View the template
3. Only var1 is output

**Expected behavior**
All params get output

**Screenshots**
<img width="967" alt="Screenshot 2021-02-18 at 10 55 37" src="https://user-images.githubusercontent.com/1846063/108346941-da576500-71d7-11eb-82ae-233469af44b6.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 11.2.1

**Comment by riasvdv** [comment]
Fixed in 1.1.4!
