### ISSUE TITLE
Items not persisting in desktop app

### ISSUE THREAD

**Issue by fthues** [spatie/craft-ray#7]
I'm using a bunch of regular `ray($variable)` calls inside a Craft CMS (Yii) plugin. The messages are displayed in the desktop app only very, very briefly (too fast to read) and the screen seems to get cleared after each one. Only the very last message is visible after the request has run.

**Versions**

Ray 1.14.6 (1.14.6)
spatie/ray 1.21.2
spatie/yii-ray 1.2.5
PHP 7.4.16
Craft CMS 3.6.10

**Expected behavior**

Show all messages on one screen.

**Screenshots**

https://user-images.githubusercontent.com/455982/112027959-fda76400-8b37-11eb-9bbf-84f494cc1cc8.mp4

**Desktop**

macOS 11.2.3

**Comment by samhibberd** [comment]
We are also running into this, shout if you need anything to help debug.

**Comment by alnassif** [comment]
@freekmurze Also having this issue, also how can we run the other ray commands inside twig template. i.e commands that are on this page https://spatie.be/docs/ray/v1/usage/reference.

**Comment by samhibberd** [comment]
@riasvdv sorry to chase, any idea on this one, only being able to see output from the last call is really frustrating :(

**Comment by riasvdv** [comment]
This should be fixed in 1.1.5, sorry for the delay

**Comment by samhibberd** [comment]
Awesome thanks @riasvdv
