### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by Antimated** [spatie/craft-ray#9]
Hey, any info on support for Ray in CraftCMS 4? Tried to install it on `Craft CMS 4.0.0-beta.1` via the plugin store but sadly it's nowhere to be found :(

**Comment by riasvdv** [comment]
We've added Craft 4 support in 2.0, this should now be visible as well in the Craft 4 plugin store!

**Comment by harrison-drift** [comment]
Seems this has removed support for Craft 3. Have to specify a version before that for it to install on <4 `composer require spatie/craft-ray:1.1.5`
